#AppDynamics user account information for the SAAS customer. Format is <appdynamics-username>@<appdynamics-account-name>
userAccount: ""

#AppDynamics password for SAAS customer
password: ""

#AppDynamics host for SAAS customer
saasHost: ""

#scheme used for REST AppD call (http/https)
protocol: "https"

applicationsUrlPath: "/controller/rest/applications"

healthRuleViolationsUrlPath: "/controller/rest/applications/<#APP_ID#>/problems/healthrule-violations?time-range-type=BEFORE_NOW&duration-in-mins=<#POLLING_FREQ_IN_MINS#>&output=XML"

eventsUrlPath: "/controller/rest/applications/<#APP_ID#>/events?time-range-type=BEFORE_NOW&duration-in-mins=<#POLLING_FREQ_IN_MINS#>&event-types=APPLICATION_ERROR,DIAGNOSTIC_SESSION&severities=ERROR&output=XML"

# Interval in mins to pull the events from REST api.
durationInMins: 1

#http timeouts in sec
connectTimeout: 10
socketTimeout: 10


#PagerDuty config for the customer
pagerDutyConfig:

   #PagerDuty Service Key
   serviceKey: ""

   #scheme used (http/https)
   protocol: "https"

   #PagerDuty url path
   host: "events.pagerduty.com"

   #PagerDuty url path
   urlPath: "/generic/2010-04-15/create_event.json"

   #http timeouts in sec
   connectTimeout: 10
   socketTimeout: 10

   #show appdynamics details in pagerduty alert
   showDetails: true

